[package]
name = "couchdb-global-changes"
version = "0.1.0"
authors = ["Johannes J. Schmidt <jo@die-tf.de>"]

[dependencies]
hyper = "0.9.10"
clap = "2.14.0"
url = "1.2.1"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
